# Projeto
sonar.projectKey=Projetosgeovane_fastfood-payment-service
sonar.organization=projetosgeovane
sonar.host.url=http://localhost:9000

# Análise de código
sonar.sources=src
sonar.exclusions=**/src/**/*.spec.ts, **/libs/**/*.spec.ts, **/src/**/*.e2e-spec.ts, **/libs/**/*.e2e-spec.ts

# Testes
sonar.tests=test
sonar.inclusions=**/src/**/*.ts, **/libs/**/*.ts

# Relatórios de cobertura
sonar.javascript.lcov.reportPaths=coverage/**/lcov.info
sonar.typescript.lcov.reportPaths=coverage/**/lcov.info

# Configuração adicional
sonar.token=sqa_7bf364a393b89ecee620d59dbaca2a403bf73e4a
