name: Deploy to Microservice Fastfood Payment Service

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build-and-deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: yarn install

    - name: Prisma generate
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: npx prisma generate

    - name: Run tests and generate coverage
      run: |
        yarn test:cov

    - name: Build project
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: yarn build

    - name: SonarCloud Scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
        SONAR_ORG_KEY: ${{ secrets.SONAR_ORG_KEY }}
      run: |
        yarn global add sonar-scanner
        sonar-scanner \
          -Dsonar.organization=${{ secrets.SONAR_ORG_KEY }} \
          -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
          -Dsonar.sources=src \
          -Dsonar.tests=test \
          -Dsonar.test.inclusions="**/*.spec.ts,**/*.test.ts" \
          -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info \
          -Dsonar.typescript.lcov.reportPaths=coverage/lcov.info

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy with Serverless
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: npx serverless deploy
